#服务配置
server:
  port: 8088
  servlet:
    context-path: /common
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责„多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这„„个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 32
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  configuration:
    log-impl : org.apache.ibatis.logging.stdout.StdOutImpl
#数据库配置
spring:
  mvc:
    static-path-pattern: /templates/**
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform:
#      jdbcUrl: jdbc:mysql://localhost:3306/mmhw?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
#      username: root
#      password: passwd
#    platform:
      jdbcUrl: jdbc:postgresql://61.153.224.202:15432/cortpdb_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: admin
      password: Cortp!pg,123
    ##  Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    ## 最小空闲连接数量
    hikari:
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池母子
      pool-name: HikariPool-zeus
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 90000
      connection-test-query: SELECT 1
  banner:
    charset: UTF-8
    http:
      encoding:
        force: true
        charset: UTF-8
    application:
      name: xx-common
    freemarker:
      request-context-attribute: request
      suffix: .ftl
      content-type: text/html
      enabled: true
      cache: false
      charset: UTF-8
      allow-request-override: false
      expose-request-attributes: true
      expose-session-attributes: true
      expose-spring-macro-helpers: true
db:
  type: postgresql